name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Save curl
        run: docker pull litmuschaos/curl:2.11.0; docker save litmuschaos/curl:2.11.0 -o litmus-curl.tar.gz
      - name: Save litmusportal-frontend
        run: docker pull litmuschaos/litmusportal-frontend:2.12.0; docker save litmuschaos/litmusportal-frontend:2.12.0 -o litmusportal-frontend.tar.gz          
      - name: Save limtmusportal-server
        run: docker pull litmuschaos/litmusportal-server:2.12.0; docker save litmuschaos/litmusportal-server:2.12.0 -o litmusportal-server.tar.gz
      - name: Save limtmusportal-auth-server
        run: docker pull litmuschaos/litmusportal-auth-server:2.12.0; docker save litmuschaos/litmusportal-auth-server:2.12.0 -o litmusportal-auth-server.tar.gz
      - name: Save mongo
        run: docker pull litmuschaos/mongo:4.2.8; docker save litmuschaos/mongo:4.2.8 -o litmus-mongo.tar.gz
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: latest_docker_image
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}

      - name: Tag release
        uses: tvdias/github-tagger@v0.0.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest_docker_image

      # Creates the new release with the binary as a release asset.
      # If the previous Action was skipped, then this keeps the same tag as the
      # previous release.
      - name: Create new release
        uses: softprops/action-gh-release@v1
        with:
          body: "Latest docker image"
          name: "latest docker image"
          tag_name: latest_docker_image
          files: |
            litmus-curl.tar.gz
            litmusportal-frontend.tar.gz
            litmusportal-server.tar.gz
            litmusportal-auth-server.tar.gz
            litmus-mongo.tar.gz
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
