name: Release

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  save-images:
    name: Save Images
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Save curl
        run: docker pull litmuschaos/curl:2.11.0; docker save litmuschaos/curl:2.11.0 -o litmus-curl.tar.gz
      - name: Save argoexec
        run: docker pull litmuschaos/argoexec:v3.3.1; docker save litmuschaos/argoexec:v3.3.1 -o litmus-argoexec.tar.gz
      - name: Save workflow controller
        run: docker pull litmuschaos/workflow-controller:v3.3.1; docker save litmuschaos/workflow-controller:v3.3.1 -o litmus-workflow-controller.tar.gz
      - name: Save chaos-operator
        run: docker pull litmuschaos/chaos-operator:2.11.0; docker save litmuschaos/chaos-operator:2.11.0 -o litmus-chaos-operator.tar.gz
      - name: Save chaos-exporter
        run: docker pull litmuschaos/chaos-exporter:2.11.0; docker save litmuschaos/chaos-exporter:2.11.0 -o litmus-chaos-exporter.tar.gz
      - name: Save chaos-runner
        run: docker pull litmuschaos/chaos-runner:2.11.0; docker save litmuschaos/chaos-runner:2.11.0 -o litmus-chaos-runner.tar.gz
      - name: Save litmusportal-frontend
        run: docker pull litmuschaos/litmusportal-frontend:2.12.0; docker save litmuschaos/litmusportal-frontend:2.12.0 -o litmusportal-frontend.tar.gz          
      - name: Save limtmusportal-server
        run: docker pull litmuschaos/litmusportal-server:2.12.0; docker save litmuschaos/litmusportal-server:2.12.0 -o litmusportal-server.tar.gz
      - name: Save limtmusportal-auth-server
        run: docker pull litmuschaos/litmusportal-auth-server:2.12.0; docker save litmuschaos/litmusportal-auth-server:2.12.0 -o litmusportal-auth-server.tar.gz
      - name: Save mongo
        run: docker pull litmuschaos/mongo:4.2.8; docker save litmuschaos/mongo:4.2.8 -o litmus-mongo.tar.gz
      - name: Save limtmusportal-subscriber
        run: docker pull litmuschaos/litmusportal-subscriber:2.12.0; docker save litmuschaos/litmusportal-subscriber:2.12.0 -o litmusportal-subscriber.tar.gz
      - name: Save limtmusportal-event-tracker
        run: docker pull litmuschaos/litmusportal-event-tracker:2.12.0; docker save litmuschaos/litmusportal-event-tracker:2.12.0 -o litmusportal-event-tracker.tar.gz
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: latest_docker_image
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}

      - name: Tag release
        uses: tvdias/github-tagger@v0.0.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest_docker_image

      # Creates the new release with the binary as a release asset.
      # If the previous Action was skipped, then this keeps the same tag as the
      # previous release.
      - name: Create new release
        uses: softprops/action-gh-release@v1
        with:
          body: "Latest docker image"
          name: "latest docker image"
          tag_name: latest_docker_image
          files: |
            litmus-curl.tar.gz
            litmus-argoexec.tar.gz
            litmus-workflow-controller.tar.gz
            litmus-chaos-operator.tar.gz
            litmus-chaos-exporter.tar.gz
            litmus-chaos-runner.tar.gz
            litmusportal-frontend.tar.gz
            litmusportal-server.tar.gz
            litmusportal-subscriber.tar.gz
            litmusportal-event-tracker.tar.gz
            litmusportal-auth-server.tar.gz
            litmus-mongo.tar.gz
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
